import numpy as np

processedFeatures = [
'nn_energyBcRestFrame',
'nn_missMass2',
'nn_q2',
'nn_missPt',
'nn_energyJpsiRestFrame',
'nn_varPt',
'nn_deltaRMu1Mu2',
'nn_phiUnpairedMu',
'nn_ptUnpairedMu',
'nn_etaUnpairedMu',
'triggerMatchDimuon0',
'triggerMatchJpsiTk',
'triggerMatchJpsiTkTk',
'signalDecayPresent',
'normalizationDecayPresent',
'background1DecayPresent']

featuresList=[
'primaryVertexX',
'primaryVertexY',
'primaryVertexZ',
'primaryVertexXError',
'primaryVertexYError',
'primaryVertexZError',
'primaryVertexXYError',
'primaryVertexYZError',
'primaryVertexXZError',
'primaryVertexChi2',
'jpsiVertexX',
'jpsiVertexY',
'jpsiVertexZ',
'jpsiVertexXError',
'jpsiVertexYError',
'jpsiVertexZError',
'jpsiVertexXYError',
'jpsiVertexYZError',
'jpsiVertexXZError',
'jpsiVertexProbability',
'bcVertexx',
'bcVertexy',
'bcVertexz',
'Bc_vertexProbability',
'Bc_charge',
'Bc_mass',
'Bc_pt',
'Bc_px',
'Bc_py',
'Bc_pz',
'Bc_eta',
'Bc_phi',
'Bc_ct',
'Bc_chi2',
'Bc_mu_charge',
'Bc_mu_pt',
'Bc_mu_px',
'Bc_mu_py',
'Bc_mu_pz',
'Bc_mu_eta',
'Bc_mu_phi',
'Bc_mu_px_noFit',
'Bc_mu_py_noFit',
'Bc_mu_pz_noFit',
'Bc_mu_eta_noFit',
'Bc_jpsi_mass',
'Bc_jpsi_pt',
'Bc_jpsi_px',
'Bc_jpsi_py',
'Bc_jpsi_pz',
'Bc_jpsi_eta',
'Bc_jpsi_phi',
'Bc_jpsi_chi2',
'Bc_jpsi_Lxy',
'Bc_jpsi_mu1_charge',
'Bc_jpsi_mu1_pt',
'Bc_jpsi_mu1_px',
'Bc_jpsi_mu1_py',
'Bc_jpsi_mu1_pz',
'Bc_jpsi_mu1_eta',
'Bc_jpsi_mu1_phi',
'Bc_jpsi_mu2_charge',
'Bc_jpsi_mu2_pt',
'Bc_jpsi_mu2_px',
'Bc_jpsi_mu2_py',
'Bc_jpsi_mu2_pz',
'Bc_jpsi_mu2_eta',
'Bc_jpsi_mu2_phi',
'jpsi_mu2_Chi2',
'jpsi_mu2_NumHits',
'jpsi_mu2_NumPixelHits',
'jpsi_mu2_Dxy',
'jpsi_mu2_Dz',
'jpsi_mu1_Chi2',
'jpsi_mu1_NumHits',
'jpsi_mu1_NumPixelHits',
'jpsi_mu1_Dxy',
'jpsi_mu1_Dz',
'muonDCA',
'triggerMatchJpsiTk',
'triggerMatchDimuon0',
'isMu1Soft',
'isMu1Global',
'isMu1Tracker',
'isMu1Tight',
'isMu1PF',
'isMu1Loose',
'isMu2Soft',
'isMu2Global',
'isMu2Tracker',
'isMu2Tight',
'isMu2PF',
'isMu2Loose',
'isMuSoft',
'isMuGlobal',
'isMuTracker',
'isMuTight',
'isMuPF',
'isMuLoose',
'signalDecayPresent',
'normalizationDecayPresent',
'background1DecayPresent',
'truthMatchMu1Sim',
'truthMatchMu2Sim',
'truthMatchMuSim',
'truthMatchMu1',
'truthMatchMu2',
'truthMatchMu']

featuresListInputs = [
'gen_b_pt',
'gen_b_px',
'gen_b_py',
'gen_b_pz',
'gen_b_E',
'gen_b_Eta',
'gen_b_Phi',
'gen_jpsi_pt',
'gen_jpsi_px',
'gen_jpsi_py',
'gen_jpsi_pz',
'gen_jpsi_E',
'gen_jpsi_Eta',
'gen_jpsi_Phi',
'gen_jpsi_mu1_pt',
'gen_jpsi_mu1_px',
'gen_jpsi_mu1_py',
'gen_jpsi_mu1_pz',
'gen_jpsi_mu1_E',
'gen_jpsi_mu1_Eta',
'gen_jpsi_mu1_Phi',
'gen_jpsi_mu2_pt',
'gen_jpsi_mu2_px',
'gen_jpsi_mu2_py',
'gen_jpsi_mu2_pz',
'gen_jpsi_mu2_E',
'gen_jpsi_mu2_Eta',
'gen_jpsi_mu2_Phi',
'gen_mu_pt',
'gen_mu_px',
'gen_mu_py',
'gen_mu_pz',
'gen_mu_E',
'gen_mu_Eta',
'gen_mu_Phi',
'gen_munu_pt',
'gen_munu_px',
'gen_munu_py',
'gen_munu_pz',
'gen_munu_E',
'gen_munu_Eta',
'gen_munu_Phi',
'gen_taunu1_pt',
'gen_taunu1_px',
'gen_taunu1_py',
'gen_taunu1_pz',
'gen_taunu1_E',
'gen_taunu1_Eta',
'gen_taunu1_Phi',
'gen_taunu2_pt',
'gen_taunu2_px',
'gen_taunu2_py',
'gen_taunu2_pz',
'gen_taunu2_E',
'gen_taunu2_Eta',
'gen_taunu2_Phi',
'bcCorrected_pt',
'bcCorrected_px',
'bcCorrected_py',
'bcCorrected_pz',
'bcCorrected_E',
'nn_MuEnergyBcRestFrame',
'nn_missMass2',
'nn_q2',
'nn_missPt',
'nn_MuEnergyJpsiRestFrame',
'nn_varPt',
'nn_deltaRMu1Mu2',
'nn_MuPhi',
'nn_MuPt',
'nn_MuEta',
'bc_E',
'jpsi_E',
'mu1_E',
'mu2_E',
'mu_E',
'primaryVertexX',
'primaryVertexY',
'primaryVertexZ',
'primaryVertexXError',
'primaryVertexYError',
'primaryVertexZError',
'primaryVertexXYError',
'primaryVertexYZError',
'primaryVertexXZError',
'primaryVertexChi2',
'jpsiVertexX',
'jpsiVertexY',
'jpsiVertexZ',
'jpsiVertexXError',
'jpsiVertexYError',
'jpsiVertexZError',
'jpsiVertexXYError',
'jpsiVertexYZError',
'jpsiVertexXZError',
'jpsiVertexProbability',
'bcVertexX',
'bcVertexY',
'bcVertexZ',
'Bc_vertexProbability',
'Bc_charge',
'Bc_mass',
'Bc_pt',
'Bc_px',
'Bc_py',
'Bc_pz',
'Bc_eta',
'Bc_phi',
'Bc_ct',
'Bc_chi2',
'Bc_mu_charge',
'Bc_mu_pt',
'Bc_mu_px',
'Bc_mu_py',
'Bc_mu_pz',
'Bc_mu_eta',
'Bc_mu_phi',
'Bc_mu_px_noFit',
'Bc_mu_py_noFit',
'Bc_mu_pz_noFit',
'Bc_mu_eta_noFit',
'Bc_jpsi_mass',
'Bc_jpsi_pt',
'Bc_jpsi_px',
'Bc_jpsi_py',
'Bc_jpsi_pz',
'Bc_jpsi_eta',
'Bc_jpsi_phi',
'Bc_jpsi_chi2',
'Bc_jpsi_Lxy',
'Bc_jpsi_mu1_charge',
'Bc_jpsi_mu1_pt',
'Bc_jpsi_mu1_px',
'Bc_jpsi_mu1_py',
'Bc_jpsi_mu1_pz',
'Bc_jpsi_mu1_eta',
'Bc_jpsi_mu1_phi',
'Bc_jpsi_mu2_charge',
'Bc_jpsi_mu2_pt',
'Bc_jpsi_mu2_px',
'Bc_jpsi_mu2_py',
'Bc_jpsi_mu2_pz',
'Bc_jpsi_mu2_eta',
'Bc_jpsi_mu2_phi',
'jpsi_mu2_Chi2',
'jpsi_mu2_NumHits',
'jpsi_mu2_NumPixelHits',
'jpsi_mu2_Dxy', 
'jpsi_mu2_Dz',
'jpsi_mu1_Chi2',
'jpsi_mu1_NumHits',
'jpsi_mu1_NumPixelHits',
'jpsi_mu1_Dxy',
'jpsi_mu1_Dz',
'muonDCA',
'triggerMatchJpsiTk',
'triggerMatchDimuon0',
'isMu1Soft',
'isMu1Global',
'isMu1Tracker',
'isMu1Tight',
'isMu1PF',
'isMu1Loose',
'isMu2Soft',
'isMu2Global',
'isMu2Tracker',
'isMu2Tight',
'isMu2PF',
'isMu2Loose',
'isMuSoft',
'isMuGlobal',
'isMuTracker',
'isMuTight',
'isMuPF',
'isMuLoose',
'signalDecayPresent',
'normalizationDecayPresent',
'background1DecayPresent',
'truthMatchMu1Sim',
'truthMatchMu2Sim',
'truthMatchMuSim',
'truthMatchMu1',
'truthMatchMu2',
'truthMatchMu']
featuresListInputsOld = [
('gen_b_pt', np.float32),
('gen_b_px', np.float32),
('gen_b_py', np.float32),
('gen_b_pz', np.float32),
('gen_b_E', np.float32),
('gen_b_Eta', np.float32),
('gen_b_Phi', np.float32),
('gen_jpsi_pt', np.float32),
('gen_jpsi_px', np.float32),
('gen_jpsi_py', np.float32),
('gen_jpsi_pz', np.float32),
('gen_jpsi_E', np.float32),
('gen_jpsi_Eta', np.float32),
('gen_jpsi_Phi', np.float32),
('gen_jpsi_mu1_pt', np.float32),
('gen_jpsi_mu1_px', np.float32),
('gen_jpsi_mu1_py', np.float32),
('gen_jpsi_mu1_pz', np.float32),
('gen_jpsi_mu1_E', np.float32),
('gen_jpsi_mu1_Eta', np.float32),
('gen_jpsi_mu1_Phi', np.float32),
('gen_jpsi_mu2_pt', np.float32),
('gen_jpsi_mu2_px', np.float32),
('gen_jpsi_mu2_py', np.float32),
('gen_jpsi_mu2_pz', np.float32),
('gen_jpsi_mu2_E', np.float32),
('gen_jpsi_mu2_Eta', np.float32),
('gen_jpsi_mu2_Phi', np.float32),
('gen_mu_pt', np.float32),
('gen_mu_px', np.float32),
('gen_mu_py', np.float32),
('gen_mu_pz', np.float32),
('gen_mu_E', np.float32),
('gen_mu_Eta', np.float32),
('gen_mu_Phi', np.float32),
('gen_munu_pt', np.float32),
('gen_munu_px', np.float32),
('gen_munu_py', np.float32),
('gen_munu_pz', np.float32),
('gen_munu_E', np.float32),
('gen_munu_Eta', np.float32),
('gen_munu_Phi', np.float32),
('gen_taunu1_pt', np.float32),
('gen_taunu1_px', np.float32),
('gen_taunu1_py', np.float32),
('gen_taunu1_pz', np.float32),
('gen_taunu1_E', np.float32),
('gen_taunu1_Eta', np.float32),
('gen_taunu1_Phi', np.float32),
('gen_taunu2_pt', np.float32),
('gen_taunu2_px', np.float32),
('gen_taunu2_py', np.float32),
('gen_taunu2_pz', np.float32),
('gen_taunu2_E', np.float32),
('gen_taunu2_Eta', np.float32),
('gen_taunu2_Phi', np.float32),
('bcCorrected_pt', np.float32),
('bcCorrected_px', np.float32),
('bcCorrected_py', np.float32),
('bcCorrected_pz', np.float32),
('bcCorrected_E', np.float32),
('nn_MuEnergyBcRestFrame', np.float32),
('nn_missMass2', np.float32),
('nn_q2', np.float32),
('nn_missPt', np.float32),
('nn_MuEnergyJpsiRestFrame', np.float32),
('nn_varPt', np.float32),
('nn_deltaRMu1Mu2', np.float32),
('nn_MuPhi', np.float32),
('nn_MuPt', np.float32),
('nn_MuEta', np.float32),
('bc_E', np.float32),
('jpsi_E', np.float32),
('mu1_E', np.float32),
('mu2_E', np.float32),
('mu_E', np.float32),
('primaryVertexX', np.float32),
('primaryVertexY', np.float32),
('primaryVertexZ', np.float32),
('primaryVertexXError', np.float32),
('primaryVertexYError', np.float32),
('primaryVertexZError', np.float32),
('primaryVertexXYError', np.float32),
('primaryVertexYZError', np.float32),
('primaryVertexXZError', np.float32),
('primaryVertexChi2', np.float32),
('jpsiVertexX', np.float32),
('jpsiVertexY', np.float32),
('jpsiVertexZ', np.float32),
('jpsiVertexXError', np.float32),
('jpsiVertexYError', np.float32),
('jpsiVertexZError', np.float32),
('jpsiVertexXYError', np.float32),
('jpsiVertexYZError', np.float32),
('jpsiVertexXZError', np.float32),
('jpsiVertexProbability', np.float32),
('bcVertexX', np.float32),
('bcVertexY', np.float32),
('bcVertexZ', np.float32),
('Bc_vertexProbability', np.float32),
('Bc_charge', np.float32),
('Bc_mass', np.float32),
('Bc_pt', np.float32),
('Bc_px', np.float32),
('Bc_py', np.float32),
('Bc_pz', np.float32),
('Bc_eta', np.float32),
('Bc_phi', np.float32),
('Bc_ct', np.float32),
('Bc_chi2', np.float32),
('Bc_mu_charge', np.float32),
('Bc_mu_pt', np.float32),
('Bc_mu_px', np.float32),
('Bc_mu_py', np.float32),
('Bc_mu_pz', np.float32),
('Bc_mu_eta', np.float32),
('Bc_mu_phi', np.float32),
('Bc_mu_px_noFit', np.float32),
('Bc_mu_py_noFit', np.float32),
('Bc_mu_pz_noFit', np.float32),
('Bc_mu_eta_noFit', np.float32),
('Bc_jpsi_mass', np.float32),
('Bc_jpsi_pt', np.float32),
('Bc_jpsi_px', np.float32),
('Bc_jpsi_py', np.float32),
('Bc_jpsi_pz', np.float32),
('Bc_jpsi_eta', np.float32),
('Bc_jpsi_phi', np.float32),
('Bc_jpsi_chi2', np.float32),
('Bc_jpsi_Lxy', np.float32),
('Bc_jpsi_mu1_charge', np.float32),
('Bc_jpsi_mu1_pt', np.float32),
('Bc_jpsi_mu1_px', np.float32),
('Bc_jpsi_mu1_py', np.float32),
('Bc_jpsi_mu1_pz', np.float32),
('Bc_jpsi_mu1_eta', np.float32),
('Bc_jpsi_mu1_phi', np.float32),
('Bc_jpsi_mu2_charge', np.float32),
('Bc_jpsi_mu2_pt', np.float32),
('Bc_jpsi_mu2_px', np.float32),
('Bc_jpsi_mu2_py', np.float32),
('Bc_jpsi_mu2_pz', np.float32),
('Bc_jpsi_mu2_eta', np.float32),
('Bc_jpsi_mu2_phi', np.float32),
('jpsi_mu2_Chi2', np.float32),
('jpsi_mu2_NumHits', np.float32),
('jpsi_mu2_NumPixelHits', np.float32),
('jpsi_mu2_Dxy', np.float32),
('jpsi_mu2_Dz', np.float32),
('jpsi_mu1_Chi2', np.float32),
('jpsi_mu1_NumHits', np.float32),
('jpsi_mu1_NumPixelHits', np.float32),
('jpsi_mu1_Dxy', np.float32),
('jpsi_mu1_Dz', np.float32),
('muonDCA', np.float32),
('triggerMatchJpsiTk', np.float32),
('triggerMatchDimuon0', np.float32),
('isMu1Soft', np.float32),
('isMu1Global', np.float32),
('isMu1Tracker', np.float32),
('isMu1Tight', np.float32),
('isMu1PF', np.float32),
('isMu1Loose', np.float32),
('isMu2Soft', np.float32),
('isMu2Global', np.float32),
('isMu2Tracker', np.float32),
('isMu2Tight', np.float32),
('isMu2PF', np.float32),
('isMu2Loose', np.float32),
('isMuSoft', np.float32),
('isMuGlobal', np.float32),
('isMuTracker', np.float32),
('isMuTight', np.float32),
('isMuPF', np.float32),
('isMuLoose', np.float32),
('signalDecayPresent', np.float32),
('normalizationDecayPresent', np.float32),
('background1DecayPresent', np.float32),
('truthMatchMu1Sim', np.float32),
('truthMatchMu2Sim', np.float32),
('truthMatchMuSim', np.float32),
('truthMatchMu1', np.float32),
('truthMatchMu2', np.float32),
('truthMatchMu', np.float32)]

featuresListResults = [
('nn_correctedRatio_pt', np.float32),
('nn_predictedRatio_pt', np.float32),
('nn_predicted_pt', np.float32),
('gen_b_pt', np.float32),
('gen_b_px', np.float32),
('gen_b_py', np.float32),
('gen_b_pz', np.float32),
('gen_b_E', np.float32),
('gen_b_Eta', np.float32),
('gen_b_Phi', np.float32),
('gen_jpsi_pt', np.float32),
('gen_jpsi_px', np.float32),
('gen_jpsi_py', np.float32),
('gen_jpsi_pz', np.float32),
('gen_jpsi_E', np.float32),
('gen_jpsi_Eta', np.float32),
('gen_jpsi_Phi', np.float32),
('gen_jpsi_mu1_pt', np.float32),
('gen_jpsi_mu1_px', np.float32),
('gen_jpsi_mu1_py', np.float32),
('gen_jpsi_mu1_pz', np.float32),
('gen_jpsi_mu1_E', np.float32),
('gen_jpsi_mu1_Eta', np.float32),
('gen_jpsi_mu1_Phi', np.float32),
('gen_jpsi_mu2_pt', np.float32),
('gen_jpsi_mu2_px', np.float32),
('gen_jpsi_mu2_py', np.float32),
('gen_jpsi_mu2_pz', np.float32),
('gen_jpsi_mu2_E', np.float32),
('gen_jpsi_mu2_Eta', np.float32),
('gen_jpsi_mu2_Phi', np.float32),
('gen_mu_pt', np.float32),
('gen_mu_px', np.float32),
('gen_mu_py', np.float32),
('gen_mu_pz', np.float32),
('gen_mu_E', np.float32),
('gen_mu_Eta', np.float32),
('gen_mu_Phi', np.float32),
('gen_munu_pt', np.float32),
('gen_munu_px', np.float32),
('gen_munu_py', np.float32),
('gen_munu_pz', np.float32),
('gen_munu_E', np.float32),
('gen_munu_Eta', np.float32),
('gen_munu_Phi', np.float32),
('gen_taunu1_pt', np.float32),
('gen_taunu1_px', np.float32),
('gen_taunu1_py', np.float32),
('gen_taunu1_pz', np.float32),
('gen_taunu1_E', np.float32),
('gen_taunu1_Eta', np.float32),
('gen_taunu1_Phi', np.float32),
('gen_taunu2_pt', np.float32),
('gen_taunu2_px', np.float32),
('gen_taunu2_py', np.float32),
('gen_taunu2_pz', np.float32),
('gen_taunu2_E', np.float32),
('gen_taunu2_Eta', np.float32),
('gen_taunu2_Phi', np.float32),
('bcCorrected_pt', np.float32),
('bcCorrected_px', np.float32),
('bcCorrected_py', np.float32),
('bcCorrected_pz', np.float32),
('bcCorrected_E', np.float32),
('nn_MuEnergyBcRestFrame', np.float32),
('nn_missMass2', np.float32),
('nn_q2', np.float32),
('nn_missPt', np.float32),
('nn_MuEnergyJpsiRestFrame', np.float32),
('nn_varPt', np.float32),
('nn_deltaRMu1Mu2', np.float32),
('nn_MuPhi', np.float32),
('nn_MuPt', np.float32),
('nn_MuEta', np.float32),
('bc_E', np.float32),
('jpsi_E', np.float32),
('mu1_E', np.float32),
('mu2_E', np.float32),
('mu_E', np.float32),
('primaryVertexX', np.float32),
('primaryVertexY', np.float32),
('primaryVertexZ', np.float32),
('primaryVertexXError', np.float32),
('primaryVertexYError', np.float32),
('primaryVertexZError', np.float32),
('primaryVertexXYError', np.float32),
('primaryVertexYZError', np.float32),
('primaryVertexXZError', np.float32),
('primaryVertexChi2', np.float32),
('jpsiVertexX', np.float32),
('jpsiVertexY', np.float32),
('jpsiVertexZ', np.float32),
('jpsiVertexXError', np.float32),
('jpsiVertexYError', np.float32),
('jpsiVertexZError', np.float32),
('jpsiVertexXYError', np.float32),
('jpsiVertexYZError', np.float32),
('jpsiVertexXZError', np.float32),
('jpsiVertexProbability', np.float32),
('bcVertexX', np.float32),
('bcVertexY', np.float32),
('bcVertexZ', np.float32),
('Bc_vertexProbability', np.float32),
('Bc_charge', np.float32),
('Bc_mass', np.float32),
('Bc_pt', np.float32),
('Bc_px', np.float32),
('Bc_py', np.float32),
('Bc_pz', np.float32),
('Bc_eta', np.float32),
('Bc_phi', np.float32),
('Bc_ct', np.float32),
('Bc_chi2', np.float32),
('Bc_mu_charge', np.float32),
('Bc_mu_pt', np.float32),
('Bc_mu_px', np.float32),
('Bc_mu_py', np.float32),
('Bc_mu_pz', np.float32),
('Bc_mu_eta', np.float32),
('Bc_mu_phi', np.float32),
('Bc_mu_px_noFit', np.float32),
('Bc_mu_py_noFit', np.float32),
('Bc_mu_pz_noFit', np.float32),
('Bc_mu_eta_noFit', np.float32),
('Bc_jpsi_mass', np.float32),
('Bc_jpsi_pt', np.float32),
('Bc_jpsi_px', np.float32),
('Bc_jpsi_py', np.float32),
('Bc_jpsi_pz', np.float32),
('Bc_jpsi_eta', np.float32),
('Bc_jpsi_phi', np.float32),
('Bc_jpsi_chi2', np.float32),
('Bc_jpsi_Lxy', np.float32),
('Bc_jpsi_mu1_charge', np.float32),
('Bc_jpsi_mu1_pt', np.float32),
('Bc_jpsi_mu1_px', np.float32),
('Bc_jpsi_mu1_py', np.float32),
('Bc_jpsi_mu1_pz', np.float32),
('Bc_jpsi_mu1_eta', np.float32),
('Bc_jpsi_mu1_phi', np.float32),
('Bc_jpsi_mu2_charge', np.float32),
('Bc_jpsi_mu2_pt', np.float32),
('Bc_jpsi_mu2_px', np.float32),
('Bc_jpsi_mu2_py', np.float32),
('Bc_jpsi_mu2_pz', np.float32),
('Bc_jpsi_mu2_eta', np.float32),
('Bc_jpsi_mu2_phi', np.float32),
('jpsi_mu2_Chi2', np.float32),
('jpsi_mu2_NumHits', np.float32),
('jpsi_mu2_NumPixelHits', np.float32),
('jpsi_mu2_Dxy', np.float32),
('jpsi_mu2_Dz', np.float32),
('jpsi_mu1_Chi2', np.float32),
('jpsi_mu1_NumHits', np.float32),
('jpsi_mu1_NumPixelHits', np.float32),
('jpsi_mu1_Dxy', np.float32),
('jpsi_mu1_Dz', np.float32),
('muonDCA', np.float32),
('triggerMatchJpsiTk', np.float32),
('triggerMatchDimuon0', np.float32),
('isMu1Soft', np.float32),
('isMu1Global', np.float32),
('isMu1Tracker', np.float32),
('isMu1Tight', np.float32),
('isMu1PF', np.float32),
('isMu1Loose', np.float32),
('isMu2Soft', np.float32),
('isMu2Global', np.float32),
('isMu2Tracker', np.float32),
('isMu2Tight', np.float32),
('isMu2PF', np.float32),
('isMu2Loose', np.float32),
('isMuSoft', np.float32),
('isMuGlobal', np.float32),
('isMuTracker', np.float32),
('isMuTight', np.float32),
('isMuPF', np.float32),
('isMuLoose', np.float32),
('signalDecayPresent', np.float32),
('normalizationDecayPresent', np.float32),
('background1DecayPresent', np.float32),
('truthMatchMu1Sim', np.float32),
('truthMatchMu2Sim', np.float32),
('truthMatchMuSim', np.float32),
('truthMatchMu1', np.float32),
('truthMatchMu2', np.float32),
('truthMatchMu', np.float32)]
